# Generated by Django 3.0.4 on 2020-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
