# Generated by Django 3.0.4 on 2020-05-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='age',
            new_name='encounters',
        ),
        migrations.RenameField(
            model_name='police',
            old_name='department',
            new_name='posting',
        ),
    ]
